-- SQL para recrear la tabla rutas
CREATE TABLE rutas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    origen VARCHAR(255) NOT NULL,
    destino VARCHAR(255) NOT NULL,
    origen_region VARCHAR(100),
    origen_provincia VARCHAR(100),
    origen_distrito VARCHAR(100),
    origen_ciudad VARCHAR(100),
    destino_region VARCHAR(100),
    destino_provincia VARCHAR(100),
    destino_distrito VARCHAR(100),
    destino_ciudad VARCHAR(100),
    fecha_salida DATE NOT NULL,
    hora_salida TIME,
    fecha_llegada DATE,
    hora_llegada TIME,
    precio DECIMAL(10,2) NOT NULL,
    capacidad_pasajeros INT DEFAULT 40,
    asientos_disponibles INT DEFAULT 40,
    duracion VARCHAR(50),
    distancia_km DECIMAL(8,2),
    descripcion TEXT,
    imagen VARCHAR(255),
    estado ENUM('activo', 'inactivo', 'mantenimiento', 'concluido') DEFAULT 'activo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- SQL para recrear la tabla rutas_concluidas
CREATE TABLE rutas_concluidas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ruta_id_original INT NOT NULL,
    origen VARCHAR(255) NOT NULL,
    destino VARCHAR(255) NOT NULL,
    origen_region VARCHAR(100),
    origen_provincia VARCHAR(100),
    origen_distrito VARCHAR(100),
    origen_ciudad VARCHAR(100),
    destino_region VARCHAR(100),
    destino_provincia VARCHAR(100),
    destino_distrito VARCHAR(100),
    destino_ciudad VARCHAR(100),
    fecha_salida DATE NOT NULL,
    hora_salida TIME,
    fecha_llegada DATE,
    hora_llegada TIME,
    precio DECIMAL(10,2) NOT NULL,
    capacidad_pasajeros INT DEFAULT 40,
    asientos_disponibles INT DEFAULT 40,
    duracion VARCHAR(50),
    distancia_km DECIMAL(8,2),
    descripcion TEXT,
    imagen VARCHAR(255),
    estado ENUM('activo', 'inactivo', 'mantenimiento', 'concluido') DEFAULT 'concluido',
    total_pasajeros_transportados INT DEFAULT 0,
    ingresos_generados DECIMAL(12,2) DEFAULT 0,
    fecha_conclusion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_fecha_salida (fecha_salida),
    INDEX idx_origen_destino (origen, destino)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
